
import React, { useState } from 'react';
import Header from './components/Header';
import Editor from './components/Editor';
import Preview from './components/Preview';
import { Language, OutputFormat, DocGenerationState } from './types';
import { docService } from './services/geminiService';
import { LANGUAGE_OPTIONS } from './constants';

const App: React.FC = () => {
  const [code, setCode] = useState<string>('');
  const [language, setLanguage] = useState<Language>(Language.Auto);
  const [docState, setDocState] = useState<DocGenerationState>({
    isLoading: false,
    content: '',
    error: null,
  });

  const handleGenerate = async () => {
    if (!code.trim()) return;

    setDocState({ ...docState, isLoading: true, error: null, content: '' });
    try {
      const result = await docService.generateDocumentation(
        code,
        language,
        // Streaming callback - update UI as chunks arrive
        (partialContent: string) => {
          setDocState(prev => ({
            ...prev,
            content: partialContent,
            isLoading: true,
          }));
        }
      );
      setDocState({
        isLoading: false,
        content: result,
        error: null,
      });
    } catch (err: any) {
      setDocState({
        isLoading: false,
        content: '',
        error: err.message || "An unexpected error occurred during documentation generation.",
      });
    }
  };

  const handleExport = async (format: OutputFormat) => {
    if (!docState.content) return;

    let blobContent: string;
    let fileName: string;
    let type: string;

    const generateHTMLWrapper = async (markdown: string) => {
      const { marked } = await import('https://esm.sh/marked');
      const htmlContent = await marked.parse(markdown);
      return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DocuMind AI - Documentation</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Inter', system-ui, -apple-system, sans-serif; line-height: 1.6; color: #1e293b; max-width: 800px; margin: 40px auto; padding: 0 24px; background: #f8fafc; }
    .card { background: white; padding: 48px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); border: 1px solid #e2e8f0; }
    h1 { font-size: 2.25rem; font-weight: 800; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-top: 0; }
    h2 { font-size: 1.5rem; font-weight: 700; margin-top: 32px; border-left: 4px solid #4f46e5; padding-left: 16px; }
    pre { background: #1e293b; color: #f8fafc; padding: 20px; border-radius: 8px; overflow-x: auto; font-size: 14px; }
    code { background: #f1f5f9; padding: 2px 4px; border-radius: 4px; color: #4f46e5; font-size: 0.9em; }
    pre code { background: transparent; padding: 0; color: inherit; }
    blockquote { border-left: 4px solid #e2e8f0; padding-left: 16px; font-style: italic; color: #64748b; }
    .footer { margin-top: 48px; text-align: center; color: #94a3b8; font-size: 0.875rem; }
    @media print {
      body { background: white; margin: 0; padding: 20px; }
      .card { box-shadow: none; border: none; padding: 0; }
    }
  </style>
</head>
<body>
  <div class="card">${htmlContent}</div>
  <div class="footer">Generated by DocuMind AI • ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
    };

    switch (format) {
      case OutputFormat.PDF:
        try {
          const html = await generateHTMLWrapper(docState.content);
          // @ts-ignore
          const html2pdf = (await import('https://esm.sh/html2pdf.js')).default;
          const options = {
            margin: 10,
            filename: `docs-${Date.now()}.pdf`,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true, letterRendering: true },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
          };
          html2pdf().from(html).set(options).save();
          return; // html2pdf handles the download
        } catch (e) {
          console.error("PDF generation failed", e);
          return;
        }

      case OutputFormat.HTML:
        try {
          blobContent = await generateHTMLWrapper(docState.content);
          fileName = `docs-${Date.now()}.html`;
          type = 'text/html';
        } catch (e) {
          blobContent = docState.content;
          fileName = `docs-${Date.now()}.md`;
          type = 'text/markdown';
        }
        break;

      case OutputFormat.JSON:
        const data = {
          content: docState.content,
          metadata: {
            language,
            timestamp: new Date().toISOString(),
            generator: "DocuMind AI"
          }
        };
        blobContent = JSON.stringify(data, null, 2);
        fileName = `docs-${Date.now()}.json`;
        type = 'application/json';
        break;

      case OutputFormat.Markdown:
      default:
        blobContent = docState.content;
        fileName = `docs-${Date.now()}.md`;
        type = 'text/markdown';
        break;
    }

    const blob = new Blob([blobContent], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-black">
      <Header />

      <main className="flex-1 flex overflow-hidden">
        {/* Sidebar */}
        <div className="w-72 bg-[#0a0a0a] border-r border-gray-800 flex flex-col p-6 space-y-8 overflow-y-auto">
          <section>
            <h3 className="text-xs font-bold text-gray-600 uppercase tracking-widest mb-4">Configuration</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-semibold text-gray-400 mb-2">Source Language</label>
                <select
                  value={language}
                  onChange={(e) => setLanguage(e.target.value as Language)}
                  className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-300 focus:ring-2 focus:ring-gray-600 focus:outline-none"
                >
                  {LANGUAGE_OPTIONS.map(opt => (
                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                  ))}
                </select>
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-xs font-bold text-gray-600 uppercase tracking-widest mb-4">Export Documentation</h3>
            <div className="grid grid-cols-1 gap-2">
              <button
                onClick={() => handleExport(OutputFormat.Markdown)}
                disabled={!docState.content}
                className="w-full flex items-center justify-start gap-3 px-4 py-2.5 bg-gray-900 text-gray-300 border border-gray-700 rounded-lg text-sm font-semibold hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Markdown (.md)
              </button>

              <button
                onClick={() => handleExport(OutputFormat.HTML)}
                disabled={!docState.content}
                className="w-full flex items-center justify-start gap-3 px-4 py-2.5 bg-gray-800 text-gray-300 border border-gray-700 rounded-lg text-sm font-semibold hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
                Export to HTML
              </button>

              <button
                onClick={() => handleExport(OutputFormat.PDF)}
                disabled={!docState.content}
                className="w-full flex items-center justify-start gap-3 px-4 py-2.5 bg-gray-800 text-gray-300 border border-gray-700 rounded-lg text-sm font-semibold hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                </svg>
                Export to PDF
              </button>

              <button
                onClick={() => handleExport(OutputFormat.JSON)}
                disabled={!docState.content}
                className="w-full flex items-center justify-start gap-3 px-4 py-2.5 bg-gray-900 text-gray-300 border border-gray-700 rounded-lg text-sm font-semibold hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
                </svg>
                Structured JSON
              </button>
            </div>
          </section>

          <section className="mt-auto">
            <div className="bg-gray-900 rounded-xl p-5 text-white shadow-lg border border-gray-800">
              <h4 className="font-bold text-sm mb-1 text-gray-400">Pro Tip</h4>
              <p className="text-xs text-gray-500 leading-relaxed">
                Include comments in your code to help the AI understand specific business constraints or complex edge cases.
              </p>
            </div>
          </section>
        </div>

        {/* Content */}
        <div className="flex-1 flex overflow-hidden p-6 gap-6 bg-[#0a0a0a]">
          <div className="flex-1 flex flex-col min-w-0">
            <Editor
              code={code}
              setCode={setCode}
              language={language}
              onGenerate={handleGenerate}
              disabled={docState.isLoading}
            />
          </div>

          <div className="flex-1 flex flex-col min-w-0 bg-[#0a0a0a] rounded-xl shadow-sm border border-gray-800 overflow-hidden relative">
            <Preview
              content={docState.content}
              isLoading={docState.isLoading}
              error={docState.error}
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;
